sudo: required
services:
  - docker

before_install: 
  - docker build -t 27930109/docker-react -f DockerFile.dev .

script: 
  - docker run -e CI=true 27930109/docker-react npm run test -- --coverage